@echo off
echo Renaming branch from main to master...
git branch -m main master
echo Pushing master branch...
git push origin master
echo Setting upstream...
git push origin --set-upstream master
echo Deleting old main branch...
git push origin --delete main
echo Done!
